skip formatting check for pull requests

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -20,8 +20,15 @@ jobs:
       - name: Setup
         uses: ./.github/actions/setup
 
-      - name: Check
-        run: pnpm check
+      - name: Check by Biome
+        run: pnpm biome ci --formatter-enabled=false --reporter=github
+
+      - name: Check by Prettier
+        # Allow formatting issues (exit code 1) but fail on syntax errors (exit code 2).
+        run: pnpm prettier --check '**/*.{html,yml,yaml,md}' || (( $? == 1 ))
+
+      - name: Check by TypeScript
+        run: pnpm tsc
 
       - name: Build
         run: pnpm build
